apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-cadavre-exquis-release-postgresql-read-0
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/read