---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cadavre-exquis-release
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: helm
      version: '6.5.*'
      sourceRef:
        kind: HelmRepository
        name: helm
      interval: 1m
  releaseName: cadavre-exquis-release
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  values:
    replicaCount: 2