dispatcher:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-dispatcher
    tag: 1.0-SNAPSHOT
  domain: cadavre-exquis.kube



register:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-register
    tag: 1.0-SNAPSHOT


subject:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT


verb:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT


adjective:
  replica: 3
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT

postgresql:
  architecture: replication
  database: "cadavre"
  auth:
    postgresPassword: "postgres"

hooks:
  pre-install:
    - name: init-db
      manifest: |-
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: init-db
        spec:
          template:
            spec:
              containers:
              - name: init-db
                image: docker.io/bitnami/postgresql:15.4.0-debian-11-r10
                command: ["./init-db.sh"]
              restartPolicy: OnFailure