dispatcher:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-dispatcher
    tag: 1.0-SNAPSHOT
  domain: cadavre-exquis.kube
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"


register:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-register
    tag: 1.0-SNAPSHOT
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

subject:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT

verb:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT

adjective:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT

postgresql:
  architecture: replication
  database: "cadavre"
  auth:
    postgresPassword: "postgres"